name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    name: Build (Vite)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: List built files
        run: ls -la ./wp-content/themes/metro/dist || true

  deploy-dev:
    name: Deploy to DEV
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: Add known_hosts (optional, safer)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Rsync theme
        run: |
          rsync -avz --delete \
            ./wp-content/themes/metro/ \
            ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:${{ secrets.DEV_PATH }}/wp-content/themes/metro/

  deploy-prod:
    name: Deploy to PROD
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production     # -> використовує environment-level secrets/правила
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Add known_hosts (optional)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Rsync theme
        run: |
          rsync -avz --delete \
            ./wp-content/themes/metro/ \
            ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PATH }}/wp-content/themes/metro/
